services:
  ydb:
    image: ydbplatform/local-ydb:24.4
    platform: linux/amd64
    hostname: localhost
    ports:
      - "2135:2135"
      - "2136:2136"
      - "8765:8765"
    environment:
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
      YDB_USE_IN_MEMORY_PDISKS: "true"
    volumes:
      - ./ydb_certs:/ydb_certs
      - ./ydb_data:/ydb_data
    restart: always
