name: Bug Report
description: File a bug report to help us improve
title: "Short description of the bug"
labels: ["bug", "triage"]
assignees:
  - danfimov

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: taskiq-ydb version
      description: What version of taskiq-ydb are you running?
      placeholder: e.g., 0.4.0
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: What version of Python are you using?
      options:
        - Python 3.9 or lower
        - Python 3.10
        - Python 3.11
        - Python 3.12
        - Python 3.13
        - Python 3.14
    validations:
      required: true

  - type: input
    id: ydb-version
    attributes:
      label: YDB version
      description: What version of YDB are you using?
      placeholder: e.g., 25.2
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: minimal-example
    attributes:
      label: Minimal code example
      description: Provide a minimal code example that reproduces the issue
      render: python
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
